mode: 'train'

model:
  name: 'resnet152'
  mlp_hidden_layer_sizes: []
  fold: [1,2,3,4,5]
  feature_vector_length: 6

dataset:
  root: '/tmp/.GoneAfterReboot/braid_dataset'
  csv_file: '/tmp/.GoneAfterReboot/spreadsheet/braid_train.csv'
  cv_subjects_dir: '/tmp/.GoneAfterReboot/cross_validation/'
  age_min: 45
  age_max: 90

optimization:
  epochs: 50
  batch_size: 6
  batch_size_mimic_factor: 1
  loss: 'MSELoss'
  optimizer:
    name: 'Adam'
    lr: !!float 1e-3 
  lr_scheduler:
    name: 'OneCycleLR'
    lr_max: !!float 1e-3
    cycle_momentum: True

output:
  weights_local_dir: '/home-local/models/2023-12-27_ResNet152/weights/'
  weights_server_dir: '/nfs/masi/gaoc11/projects/BRAID/models/2023-12-27_ResNet152/weights/'
  tensorboard: '/nfs/masi/gaoc11/projects/BRAID/models/2023-12-27_ResNet152/runs/'
  png_sanity_check: '/nfs/masi/gaoc11/projects/BRAID/models/2023-12-27_ResNet152/sanity_check/'

